"""
stocks4cas - documentary builder

Reads this repository and writes:

    docs.js          the bundle documentary.js renders into the documentary
                     at the bottom of every page: the full source of every
                     hand-written file, the run logs, and a SHA-256 for each
                     generated output;
    data/docs.json   the same manifest, in plain JSON, for inspection;
    data/docs.log    the build report (including the checksum of docs.js
                     itself, which cannot be stored inside docs.js).

Nothing is generated that is not already in the repository: no network
access, no rewriting of the sources.

Run with:  python build_docs.py
"""

import hashlib
import json
import os
import sys
from datetime import date

ROOT = os.path.dirname(os.path.abspath(__file__))

# Hand-written files, quoted in full. The order is the tab order on the page.
SOURCE_FILES = [
    "README.md",
    "requirements.txt",
    ".gitignore",
    "simulate.py",
    "fetch_news.py",
    "build_docs.py",
    "build.py",
    "theme.js",
    "common.js",
    "documentary.js",
    "script.js",
    "analysis.js",
    "simulation.js",
    "news.js",
    "news-page.js",
    "about.js",
    "style.css",
    "index.html",
    "analysis.html",
    "simulation.html",
    "news.html",
    "about.html",
]

# Logs are quoted as text (they are the point of the logs chapter).
LOG_FILES = ["data/run.log", "data/news.log"]

# Generated outputs are listed as name + size + hash, never quoted back in.
OUTPUT_FILES = [
    "data/strategies.json",
    "data/equity.json",
    "data/trades.json",
    "data/prices.json",
    "data/trades.csv",
    "data.js",
    "news-data.js",
]

LANGUAGES = {
    ".py": "python",
    ".js": "javascript",
    ".html": "html",
    ".css": "css",
    ".md": "markdown",
    ".txt": "text",
}


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def rel_path(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def describe(path):
    full = os.path.join(ROOT, path)
    return {
        "path": rel_path(full),
        "bytes": os.path.getsize(full),
        "sha256": sha256(full),
    }


def main():
    log = []

    def say(line=""):
        log.append(line)
        print(line)

    say("=== stocks4cas documentary build ===")

    files = []
    missing = []
    for path in SOURCE_FILES:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            missing.append(path)
            continue
        with open(full, encoding="utf-8-sig") as f:
            source = f.read()
        entry = describe(path)
        entry.update({
            "lang": LANGUAGES.get(os.path.splitext(path)[1], "text"),
            "lines": source.count("\n") + (0 if source.endswith("\n") else 1),
            "source": source,
        })
        files.append(entry)
        say(f"  {entry['path']:22} {entry['lines']:>5} lines  {entry['bytes']:>8,} bytes")

    logs = []
    for path in LOG_FILES:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            missing.append(path)
            continue
        with open(full, encoding="utf-8") as f:
            text = f.read()
        entry = describe(path)
        entry["text"] = text
        logs.append(entry)
        say(f"  {entry['path']:22} {'log':>5}        {entry['bytes']:>8,} bytes")

    outputs = []
    for path in OUTPUT_FILES:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            missing.append(path)
            continue
        entry = describe(path)
        outputs.append(entry)
        say(f"  {entry['path']:22} {'generated':>10}  {entry['bytes']:>8,} bytes")

    trades_path = os.path.join(ROOT, "data", "trades.json")
    trade_count = 0
    if os.path.exists(trades_path):
        with open(trades_path, encoding="utf-8") as f:
            trade_count = len(json.load(f))

    docs = {
        "generated": date.today().isoformat(),
        "generator": "build_docs.py",
        "note": (
            "Everything below is read from the repository at build time. Generated bundles "
            "(data.js, news-data.js) appear as hashes instead of being quoted back into themselves; "
            "docs.js records its own checksum in data/docs.log."
        ),
        "totalLines": sum(f["lines"] for f in files),
        "tradeCount": trade_count,
        "files": files,
        "logs": logs,
        "outputs": outputs,
        "missing": missing,
    }

    bundle_path = os.path.join(ROOT, "docs.js")
    with open(bundle_path, "w", encoding="utf-8-sig") as f:
        f.write("// Auto-generated by build_docs.py - do not edit by hand.\n")
        f.write("const DOCS = " + json.dumps(docs) + ";\n")

    manifest_path = os.path.join(ROOT, "data", "docs.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump({k: v for k, v in docs.items() if k != "files"} | {"files": [{k: v for k, v in fi.items() if k != "source"} for fi in files]}, f, indent=2)

    say("")
    say(f"source files : {len(files)} ({docs['totalLines']:,} lines)")
    say(f"run logs     : {len(logs)}")
    say(f"outputs      : {len(outputs)}")
    say(f"trades       : {trade_count}")
    if missing:
        say(f"missing      : {', '.join(missing)}")
    say(f"wrote bundle -> {bundle_path} ({os.path.getsize(bundle_path):,} bytes)")
    say(f"wrote manifest -> {manifest_path}")

    log_path = os.path.join(ROOT, "data", "docs.log")
    say(f"docs.js sha256: {sha256(bundle_path)}")
    say(f"wrote log    -> {log_path}")
    with open(log_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(log) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
